# Generated by Django 4.1.4 on 2023-10-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Music_Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_Title', models.CharField(max_length=125)),
                ('ablums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerApp.album')),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerApp.artist')),
                ('durations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerApp.duration')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerApp.genre')),
            ],
        ),
    ]
