# Generated by Django 4.1.4 on 2023-10-22 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("PlayerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayLists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Playlist_Title",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="music_uploader",
            name="durations",
        ),
        migrations.AddField(
            model_name="music_uploader",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="File size must be 5 MB or less",
                null=True,
                upload_to="Songs/All_Songs",
            ),
        ),
        migrations.AddField(
            model_name="music_uploader",
            name="duration",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="music_uploader",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="Songs/Song_images/"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="album",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="artist",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="genre",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="music_uploader",
            name="Song_Title",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.DeleteModel(
            name="Duration",
        ),
        migrations.AddField(
            model_name="playlists",
            name="Songs",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="playlists",
                to="PlayerApp.music_uploader",
            ),
        ),
        migrations.AddField(
            model_name="playlists",
            name="User_Name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
