# Generated by Django 4.1.4 on 2023-10-22 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PlayerApp", "0002_playlists_remove_music_uploader_durations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music_uploader",
            name="duration",
        ),
    ]
