"""
Django settings for MusicPlayerProject project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+i4&zmmrrq)ivm##yli)y9tje8ll*iia^hbj0=pkxds@n0doo_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PlayerApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MusicPlayerProject.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MusicPlayerProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Smtp Email configuration setup here
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'Your-Smtp-Email-Here'
EMAIL_HOST_PASSWORD = 'Your-Smtp-Password-Here'

import os
# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# firebase otp configuration
# import firebase_admin
# from firebase_admin import credentials

# # Construct the path to your Firebase Admin SDK credentials JSON file
# FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'config', 'C:/Users/user/Desktop/GitMusicPlayer/MusicPlayerProject/MusicPlayerProject/adminsdk.json')

# # Firebase Admin SDK configuration
# cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
# firebase_admin.initialize_app(cred)

# jazzmin.py

from django.utils.translation import gettext_lazy as _
from .jazzmin import CUSTOM_MODEL_ICONS  # Import the custom model icons

JAZZMIN_SETTINGS = {
    "custom_model_icons": CUSTOM_MODEL_ICONS,  # Set custom model icons
}


JAZZMIN_SETTINGS = {
    "site_title": _("Music Player Admin"),  # Set your custom title here
    "site_header": "Music Player Admin",
    "site_brand": "Music Player Admin",
    "site_logo": "C:/Users/user/Desktop/GitMusicPlayer/MusicPlayerProject/static/music.jpg",
    "welcome_sign": "Welcome to Music Player Administration ",
    "show_ui_builder": False,
    
}

# DJANGO_ADMIN_SIDEBAR_TITLE = "Custom Sidebar Title"

JAZZMIN_UI_TWEAKS = {
    "theme": "lumen",  # Choose a theme or customize your own
    "title": _("Music Player Admin"),
    "related_modal_active": True,
    "navbar_small_text": _("My Admin"),
}
